/* eslint-disable react/no-unescaped-entities */
/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Avatar from "../components/Avatar";
import {
  MicrophoneIcon,
  SearchIcon,
  ViewGridIcon,
} from "@heroicons/react/solid";
import Image from "next/dist/client/future/image";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;
    if (!term) return;
    router.push(`/search?term=${term}`);
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google Search Engine 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://icons-for-free.com/iconfiles/png/512/Google-1320568266385361674.png"
        />
      </Head>
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        <div className="flex space-x-4 items-center">{/*left menu */}</div>
        {/*right menu*/}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail </p>
          <p className="link">Images </p>
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer " />
          <Avatar url="https://lh3.googleusercontent.com/ogw/AOh-ky0lhH3gj1Gl9jVLrDNImC8kAtcJtsSiCAtFTxf1=s32-c-mo" />
        </div>
      </header>

      <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
        <Image
          src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          height={100}
          width={300}
        />

        <div
          className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg
                      bg-white 
                      dark:hover:bg-gray-500 dark:hover:bg-gray max-w-md rounded-full border
                      border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl "
        >
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchInputRef}
            type="text"
            className="flex-grow focus:outline-none  "
          />
          <MicrophoneIcon className="h-5 mr-3" />
        </div>

        <div
          className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0
                     sm:flex-row sm:space-x-4"
        >
          <button onClick={search} className="btn">
            Google Search
          </button>
          <button onClick={search} className="btn">
            I'm Feeling Lucky
          </button>
        </div>
      </form>
      {/*footer*/}
      <Footer />
    </div>
  );
}
